version: 2.1
workflows:
  main:
    jobs:
      - build

jobs:
  build:
    working_directory: /go/src/github.com/xenking/xlsx
    executor:
      name: go/postgres-redis
      go-tag: '1.15'
    steps:
      - checkout
      - go/fetch
      - go/test
      - go/lint
      - codecov/upload:
          file: /tmp/cover-results/cover.out

orbs:
  go: streamroot/go-check@0.2.0
  codecov: codecov/codecov@1.1.3